name: Tag Latest Version

on:
  workflow_call:
    
jobs:
  tag:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm --no-git-tag-version version prerelease --preid=pre
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: package-version-to-git-tag
      uses: pkgdeps/git-tag-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_repo: ${{ github.repository }}
        git_commit_sha: ${{ github.sha }}
        version: ${{ steps.package-version.outputs.current-version}}
        git_tag_prefix: "v"
#    - run: echo ${{ steps.package-version.outputs.current-version}}
