on:
  workflow_call:
    inputs:
      junk:
        default: ''
        type: string
    
jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - run: npm version prerelease --preid=pre
    - run: git push origin main
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - run: npm ci
    - run: npm run build
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: js-codeformer-${{ steps.package-version.outputs.current-version }}.vsix
        asset_name: js-codeformer-${{ steps.package-version.outputs.current-version }}.vsix
        tag: v${{ steps.package-version.outputs.current-version }}
        overwrite: true
        body: "JS CodeFormer Prerelease v${{ steps.package-version.outputs.current-version }}"
