
name: Test And Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: cmstead/js-codeformer/.github/workflows/node.js.yml@866c2504302451517c8d31a921137f042da72518
  tag:
    uses: cmstead/js-codeformer/.github/workflows/new-tag.yml@866c2504302451517c8d31a921137f042da72518
