
name: Test And Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: cmstead/js-codeformer/.github/workflows/tests.yml@b77ad12eea1ea1714d5dd5bf9ee2bd08c5be53c0
  tag:
    if: success()
    uses: cmstead/js-codeformer/.github/workflows/new-tag.yml@0c491c14e519e62dd78dee870e9f6dfd8e272744
