
name: Test And Release

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: cmstead/js-codeformer/.github/workflows/tests.yml@df75378e06f412be582ac5690eae509bfaaff0c9
  tag:
    needs: test
    uses: cmstead/js-codeformer/.github/workflows/new-tag.yml@025d1b89e485bfea75c99a6009f1aea1f646bf68
