
name: Test And Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: cmstead/js-codeformer/.github/workflows/node.js.yml@c63ba5daf6ee7589a34292c49663a823ebc78e2e
  tag:
    uses: cmstead/js-codeformer/.github/workflows/new-tag.yml@c63ba5daf6ee7589a34292c49663a823ebc78e2e
